apiVersion: v1
kind: ReplicationController
metadata:
  name: devops-capstone-app
spec:
  replicas: 5
  selector:
    app: devops-capstone-app
  template:
    metadata:
      name: devops-capstone-app
      labels:
        app: devops-capstone-app
    spec:
      containers:
        - name: devops-capstone-app
          image: mhoward22/devops-capstone-app:<BUILD_NUMBER>
          ports:
            - containerPort: 8080
              name: http-server
